server:
  port: 9090
  servlet:
    context-path: /learning

mybatis:
  mapperLocations: classpath:mybatis/mapping/*.xml
  typeAliasesPackage: com.zdran.springboot.dao

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LEARNING
    username: root
    password: ******
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    keepAlive: true
    removeAbandoned: true
    removeAbandonedTimeout: 80
    logAbandoned: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,slf4j,wall

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  redis:
    cluster:
      nodes: 127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003
    password:
    timeout: 10000ms
    database: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 1
        max-active: 8
        max-wait: 6000ms
